### ISSUE TITLE
Creating recipient's output should not involve his private key

### ISSUE THREAD

**Issue by tka85** [bitcoin-studio/bitcoin-test-wallets-generator#2]
I see this across several scenarios like for example in `Simple Transaction (1 input, 1 output) - Legacy P2PKH`. To add the recipient's output in the tx, you use his priv key:

```
const keyPairBob1 = bitcoin.ECPair.fromWIF(bob[1].wif, network)
const p2pkhBob1 = bitcoin.payments.p2pkh({pubkey: keyPairBob1.publicKey, network})
...
txb.addOutput(p2pkhBob1.address, ...)
```

This gives the false impression that to send to someone I need to have his WIF. 

The example could instead just use directly Bob's publicKey from the wallets.json. It still shows how to construct a p2pkh address using bitcoinjs and also maintains that only public info is required from the recipient:

```
const p2pkhBob1 = bitcoin.payments.p2pkh({pubkey: Buffer.from(bob[1].pubKey, 'hex'), network})
...
txb.addOutput(p2pkhBob1.address, ...)
```

**Comment by Janaka-Steph** [comment]
Hello,

This issue should have been open on the bitcoinjs tutorial repo, but never mind. 
Well, you are right, but I use this construct all over the tutorial and I am too lazy to change everything. 
If I have enough motivation to work on a tuto for bitcoinjs v5 one of these days I will follow your suggestion.
